### ISSUE TITLE
Move calibration files (and reduction scripts) into one separate location

### ISSUE THREAD

**Issue by Anders-Markvardsen** [ISISScientificComputing/autoreduce#219] opened 2018-10-26 06:58 UTC
Currently we have calibrations files 

1. in `\\autoreduce\InstrumentFiles\` which is a samba share on autoreduce compute node
2. in each `\\isis\inst$\NDX$$$\user\scripts\autoreduction\` or subfolders of these

1 was created as a temporary solution to drop very large calibration files since the `\user\` folders of `\\isis\inst$` are not designed to hold very large files.

Purpose of this issue is to crease one location for calibration files while
* while ensuring relevant read/write/access permissions
* backed up
* fast read speed from compute nodes (or alternative have these files are sync to area(s) with fast read speed from compute nodes)

It may also make sense to move the reduction scripts to this located at the same time? These needs the same read/write/access permissions etc. as for the calibration files.

**Comment by Anders-Markvardsen** [comment] 2018-10-26 06:58
Put as low priority for now since other issues currently higher priority

**Comment by ElliotAOram** [comment] 2019-03-18 13:43
Duplicate of #8

**Closed by ElliotAOram** 2019-03-18 13:43 UTC
Labels: :bust_in_silhouette: Developer Requirement, :clock1: Low priority, :key: Internal
