### ISSUE TITLE
All rows in runs:list have id="top-run-number"

### ISSUE THREAD

**Issue by dtasev** [ISISScientificComputing/autoreduce#1143] opened 2021-02-23 18:58 UTC
Issue raised by: [developer/user/project requirement]

### What?
All rows in runs:list have id="top-run-number". ID's should be unique, but all the rows have that. 

It seems that this ID is used for the tour to highlight the first row, and that works thank to how nice JS is (multiple matches returns first anyway). We should fix it anyway.

### Where?
Should be runs_list.html, probably the `for run in paginator.current_page.records` loop. 

### How?
How did the issue come about

### Reproducible?
[Yes/No]

### How to test the issue is resolved
A set of instructions / A script / Include test files if required

**Comment by keiranjprice101** [comment] 2021-02-24 09:07
Duplicate of #1023 which is fixed in #1021

**Closed by keiranjprice101** 2021-02-24 09:07 UTC
Labels: :key: WebApp, New Starter
