### ISSUE TITLE
Add tests for queue processors

### ISSUE THREAD

**Issue by Anders-Markvardsen** [ISISScientificComputing/autoreduce#7] opened 2018-03-19 13:19 UTC
Issue should cover adding new unit tests the the `AutoReductionProcessor` and the `QueueProcessor` with a view to improving robustness. Later these should be migrated to automated tests with a CI tool.
* [x] Assess what is currently in place to test the queue processor**s**.
  * Nothing currently
* [x] Investigate what tests we require - match the test criteria to the common faults (investigate these if unknown)
  * Currently unknown so will start with base cases for testing / setting up a structure to enable testing
* [ ] Write unit tests to cover test cases.

**Comment by ElliotAOram** [comment] 2019-03-07 08:42
Closing this as it is now duplicate of #230

**Closed by ElliotAOram** 2019-03-07 08:42 UTC
Labels: :bust_in_silhouette: Project Requirement, :key: Testing
